### ISSUE TITLE
'SKIP_PREFLIGHT_CHECK' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by navidsotoudeh** [tailwindcomponents/cheatsheet#11]
Hi, after yarn install done and i write yarn start i get this error !  :
'SKIP_PREFLIGHT_CHECK' is not recognized as an internal or external command, operable program or batch file.
 
 how can i fix it ?

thanks

**Comment by khatabwedaa** [comment]
Hi @navidsotoudeh, I didn't have any errors when clone the repo and try to run it pls check your node version and yarn version.
