### ISSUE TITLE
Deploy repo to website for V3 support

### ISSUE THREAD

**Issue by Maybach91** [tailwindcomponents/cheatsheet#12]
Hej,

when are you planning to update the website? Since the repo supports Tailwind V3 already (@khatabwedaa (https://github.com/tailwindcomponents/cheatsheet/commit/9b115dfdbfa7235e43fcd04b721529a9609b81d1)) and i think the cheatsheet is also already updated?

I see the `max-height` values are not updated yet.

Thank you for your work! :)

**Comment by khatabwedaa** [comment]
Hi, will deploy tomorrow :smile:
