### ISSUE TITLE
make base font size customisable

### ISSUE THREAD

**Issue by szamanr** [tailwindcomponents/cheatsheet#19]
## problem

tailwind takes 16px as the default base font value and all the values are derived from it. if you customise your base font, then the pixel values displayed in the cheatsheet are not accurate.

## solution

add a setting to customise the base font value and store it in local storage. the pixel values should take it into account when calculating.

so for example this:
`max-h-1 | max-height: 0.25rem; | 4px`

would become this if your base font is 15px:
`max-h-1 | max-height: 0.25rem; | 3.75px`

**Comment by killgt** [comment]
A cheatsheet is for quick reference, there's no need to be accurate, it's a cool idea, but probably no one will use it

**Comment by khatabwedaa** [comment]
It's a nice idea, but our cheatsheet is built to be a reference for the newbie, and help people know the CSS code for tailwind classes.

It's for default tailwindcss about. 

Thanks for your suggestion.
