### ISSUE TITLE
Search by category name

### ISSUE THREAD

**Issue by IlyaSmagin** [tailwindcomponents/cheatsheet#33]
## I think it would be nice if I could be searching by category name, especially when starting on expanded view

Here is an example for searching effects category:

#### initial view
![initial view](https://github.com/tailwindcomponents/cheatsheet/assets/19977559/d77c4746-3f30-4521-8fef-91eed7130c1f)
#### `eff` search 
![search effects](https://github.com/tailwindcomponents/cheatsheet/assets/19977559/2fa61a61-526a-457d-8311-83ab3186a617)

The only possible problem is that after accepting this change some search results will change, 'cause more results will be visible, here is example for `spacing` search query:

#### old
![old spacing](https://github.com/tailwindcomponents/cheatsheet/assets/19977559/fa34b150-984c-41c7-80fb-51c9fd7c5667)
#### new
![new spacing](https://github.com/tailwindcomponents/cheatsheet/assets/19977559/01ddd1c8-2462-49ac-b8d0-d53b5bc0a3eb)

I believe this will greatly improve user experience and I've already implemented this change in my #32 PR
Any feedback is appreciated!

**Comment by khatabwedaa** [comment]
Merged!
