### ISSUE TITLE
Generate cheatsheet from custom tailwind.config.js

### ISSUE THREAD

**Issue by UnsolvedCypher** [tailwindcomponents/cheatsheet#5]
It would be nice to be able to specify a custom tailwind.config.js file and have the values in the cheatsheet correspond to those rather than the defaults.

**Comment by killgt** [comment]
I'm not really sure how to go about this, because we actually have hardcoded all the utilities and we'll need to generate then dinamically to allow it

**Comment by maddog986** [comment]
> I'm not really sure how to go about this, because we actually have hardcoded all the utilities and we'll need to generate then dinamically to allow it

Dynamically build the cheatsheet.json based off the config file?

**Comment by killgt** [comment]
I don't think it's an easy task 😅 

PRs are welcome

**Comment by khatabwedaa** [comment]
Hi @UnsolvedCypher, for now, I think this is not possible because we build a cheatsheet.json statically.

But we will discover this in the future.
