### ISSUE TITLE
Broken link to Tailwind documentation

### ISSUE THREAD

**Issue by robinsonjohn** [tailwindcomponents/cheatsheet#8]
First, I must say that this cheatsheet is incredible! Thank you for all your work.

I noticed that the link to Tailwind's documentation is broken in the `Backgrounds > Gradient Color Stops` section.

Current link: https://tailwindcss.com/docs/bacgradient-color-stops
Correct link: https://tailwindcss.com/docs/gradient-color-stops

**Comment by khatabwedaa** [comment]
Fixed! Thanks @robinsonjohn
