### ISSUE TITLE
Update cheatsheet to Tailwind 3.0

### ISSUE THREAD

**Issue by UnsolvedCypher** [tailwindcomponents/cheatsheet#9]
Tailwind 3.0 has finally been released with a number of new features: https://tailwindcss.com/blog/tailwindcss-v3

**Comment by khatabwedaa** [comment]
Working on it :smile:

**Comment by zcyc** [comment]
hi, when release it? @khatabwedaa

**Comment by khatabwedaa** [comment]
> hi, when release it? @khatabwedaa

as soon as I finished it hehe

**Comment by dawidmachon** [comment]
Any news? How can we help you to upgrade it? It's much more friendly than official site.

**Comment by khatabwedaa** [comment]
Hi, It's Already Done wait for the owner to merge.
